Repository masters2023-project-team05-second-hand/second-hand-max-be-a, pull requests merged in 2023-10, with the labels that each got.

#88 [BE] 모든 카테고리를 조회하는 아이디의 의미가 드러나게 상수로 변경
  be/src/main/java/team05a/secondhand/wish/service/WishService.java
Labels: ♻️refactor

#90 [BE] 채팅방 생성 기능 구현
  be/src/main/java/team05a/secondhand/chat/controller/ChatController.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatRoomCreateRequest.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatRoomUuidResponse.java
  be/src/main/java/team05a/secondhand/chat/data/dto/MessageCreateRequest.java
  be/src/main/java/team05a/secondhand/chat/data/entity/ChatRoom.java
  be/src/main/java/team05a/secondhand/chat/data/entity/Message.java
  be/src/main/java/team05a/secondhand/chat/repository/ChatRoomRepository.java
  be/src/main/java/team05a/secondhand/chat/repository/MessageRepository.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/main/java/team05a/secondhand/errors/exception/BuyerIdAndMessageSenderIdNotSameException.java
  be/src/main/java/team05a/secondhand/errors/exception/ChatRoomExistsException.java
  be/src/main/java/team05a/secondhand/errors/exception/SellerIdAndBuyerIdSameException.java
  be/src/main/java/team05a/secondhand/errors/handler/ChatExceptionHandler.java
  be/src/test/java/team05a/secondhand/chat/integration/ChatTest.java
Labels: ✨feat

#92 [BE]: 채팅방 존재 여부 조회 기능 구현
  be/src/main/java/team05a/secondhand/chat/controller/ChatController.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatRoomUuidResponse.java
  be/src/main/java/team05a/secondhand/chat/repository/ChatRoomRepository.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/test/java/team05a/secondhand/chat/integration/ChatTest.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
Labels: ✨feat

#95 [BE]: 프론트와 회의후 리팩토링
  be/src/main/java/team05a/secondhand/chat/controller/ChatController.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatRoomCreateRequest.java
  be/src/main/java/team05a/secondhand/chat/data/dto/MessageCreateRequest.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/test/java/team05a/secondhand/chat/integration/ChatTest.java
Labels: ♻️refactor

#98 [BE] 채팅방 목록 조회 구현
  be/src/main/java/team05a/secondhand/chat/controller/ChatController.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatProductResponse.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatRoomLastMessageResponse.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatRoomListResponse.java
  be/src/main/java/team05a/secondhand/chat/data/entity/ChatRoom.java
  be/src/main/java/team05a/secondhand/chat/repository/ChatRoomRepository.java
  be/src/main/java/team05a/secondhand/chat/repository/ChatRoomRepositoryCustom.java
  be/src/main/java/team05a/secondhand/chat/repository/ChatRoomRepositoryImpl.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/test/java/team05a/secondhand/chat/integration/ChatRestAssuredTest.java
  be/src/test/java/team05a/secondhand/chat/repository/ChatRepositoryTest.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
Labels: ✨feat, ✅test, ✏️review

#100 [BE] 메세지 조회 구현
  be/src/main/java/team05a/secondhand/chat/controller/ChatController.java
  be/src/main/java/team05a/secondhand/chat/data/dto/MessageReadResponse.java
  be/src/main/java/team05a/secondhand/chat/repository/MessageRepository.java
  be/src/main/java/team05a/secondhand/chat/repository/MessageRepositoryCustom.java
  be/src/main/java/team05a/secondhand/chat/repository/MessageRepositoryImpl.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/main/java/team05a/secondhand/errors/exception/IllegalChatRoomParticipantException.java
  be/src/main/java/team05a/secondhand/errors/handler/ChatExceptionHandler.java
  be/src/test/java/team05a/secondhand/chat/integration/ChatRestAssuredTest.java
Labels: ✨feat, ✅test, ✏️review

#97 [BE] 실시간 채팅 기능 구현
  be/build.gradle
  be/src/main/java/team05a/secondhand/chat/controller/ChatMessageController.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatMessageCreateRequest.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatMessageResponse.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/main/java/team05a/secondhand/config/WebSocketConfig.java
  be/src/main/java/team05a/secondhand/filter/JwtAuthorizationFilter.java
  be/src/main/java/team05a/secondhand/interceptor/ChatPreHandler.java
Labels: ✨feat

#104 [BE] 채팅방 나가기 구현
  be/src/main/java/team05a/secondhand/chat/controller/ChatController.java
  be/src/main/java/team05a/secondhand/chat/data/entity/ChatRoom.java
  be/src/main/java/team05a/secondhand/chat/repository/ChatRoomRepository.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/test/java/team05a/secondhand/chat/integration/ChatRestAssuredTest.java
Labels: ✨feat, ✅test, ✏️review

#103 [BE]: 자잘한 리팩토링 구현
  be/src/main/java/team05a/secondhand/chat/controller/ChatController.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatRoomCreateResponse.java
  be/src/main/java/team05a/secondhand/chat/data/dto/ChatRoomIdResponse.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/test/java/team05a/secondhand/chat/integration/ChatTest.java
Labels: ♻️refactor

#113 [BE] 채팅방 나가기 및 목록 조회 리팩토링
  be/src/main/java/team05a/secondhand/chat/data/entity/ChatRoom.java
  be/src/main/java/team05a/secondhand/chat/repository/ChatRoomRepository.java
  be/src/main/java/team05a/secondhand/chat/repository/ChatRoomRepositoryImpl.java
  be/src/main/java/team05a/secondhand/chat/repository/MessageRepositoryImpl.java
  be/src/main/java/team05a/secondhand/chat/service/ChatService.java
  be/src/main/java/team05a/secondhand/errors/exception/ChatRoomNotFoundException.java
  be/src/main/java/team05a/secondhand/errors/handler/ChatExceptionHandler.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
Labels: ♻️refactor, ✏️review
