Repository masters2023-project-team05-second-hand/second-hand-max-be-a, pull requests merged in 2023-09, with the labels that each got.

#11 [BE] cors 설정
  be/src/main/java/team05a/secondhand/config/FilterConfig.java
  be/src/main/java/team05a/secondhand/filter/CorsFilter.java
Labels: ✨feat

#16 [BE] 주소 목록 조회 구현
  be/src/main/java/team05a/secondhand/address/controller/AddressController.java
  be/src/main/java/team05a/secondhand/address/data/dto/AddressListResponse.java
  be/src/main/java/team05a/secondhand/address/data/entity/Address.java
  be/src/main/java/team05a/secondhand/address/service/AddressService.java
  be/src/main/resources/data.sql
  be/src/test/java/team05a/secondhand/ControllerTestSupport.java
  be/src/test/java/team05a/secondhand/IntegrationTestSupport.java
  be/src/test/java/team05a/secondhand/address/controller/AddressControllerTest.java
  be/src/test/java/team05a/secondhand/address/integration/AddressTest.java
  be/src/test/java/team05a/secondhand/address/repository/AddressRepositoryTest.java
  be/src/test/java/team05a/secondhand/address/service/AddressServiceTest.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
Labels: ✨feat, ✅test, ✏️review

#20 [BE] 로그인 api 변경
  be/src/main/java/team05a/secondhand/filter/JwtAuthorizationFilter.java
  be/src/main/java/team05a/secondhand/jwt/Jwt.java
  be/src/main/java/team05a/secondhand/jwt/JwtTokenProvider.java
  be/src/main/java/team05a/secondhand/member/controller/MemberController.java
  be/src/main/java/team05a/secondhand/member/data/dto/MemberAddressResponse.java
  be/src/main/java/team05a/secondhand/member/data/dto/MemberAddressUpdateRequest.java
  be/src/main/java/team05a/secondhand/member/data/dto/MemberResponse.java
  be/src/main/java/team05a/secondhand/member/data/entity/Member.java
  be/src/main/java/team05a/secondhand/member/service/MemberService.java
  be/src/main/java/team05a/secondhand/member_address/data/entity/MemberAddress.java
  be/src/main/java/team05a/secondhand/member_address/repository/MemberAddressRepository.java
  be/src/main/java/team05a/secondhand/oauth/controller/OauthController.java
  be/src/main/java/team05a/secondhand/oauth/data/dto/LoginResponse.java
  be/src/main/java/team05a/secondhand/oauth/data/dto/MemberLoginResponse.java
  be/src/main/java/team05a/secondhand/oauth/service/OauthService.java
  be/src/test/java/team05a/secondhand/member/integration/MemberIntegrationTest.java
Labels: ✨feat, 🐛fix, ✅test

#21 [BE] 상품 등록 API 구현
  be/build.gradle
  be/src/main/java/team05a/secondhand/address/data/entity/Address.java
  be/src/main/java/team05a/secondhand/category/data/entity/Category.java
  be/src/main/java/team05a/secondhand/config/WebConfig.java
  be/src/main/java/team05a/secondhand/errors/ErrorResponse.java
  be/src/main/java/team05a/secondhand/errors/errorcode/CommonErrorCode.java
  be/src/main/java/team05a/secondhand/errors/errorcode/ImageErrorCode.java
  be/src/main/java/team05a/secondhand/errors/errorcode/OauthErrorCode.java
  be/src/main/java/team05a/secondhand/errors/exception/AddressNotFoundException.java
  be/src/main/java/team05a/secondhand/errors/exception/CategoryNotFoundException.java
  be/src/main/java/team05a/secondhand/errors/exception/ImageCountOutOfRangeException.java
  be/src/main/java/team05a/secondhand/errors/exception/ImageUploadFailedException.java
  be/src/main/java/team05a/secondhand/errors/exception/MemberNotFoundException.java
  be/src/main/java/team05a/secondhand/errors/exception/StatusNotFoundException.java
  be/src/main/java/team05a/secondhand/errors/handler/AddressExceptionHandler.java
  be/src/main/java/team05a/secondhand/errors/handler/CategoryExceptionHandler.java
  be/src/main/java/team05a/secondhand/errors/handler/GlobalExceptionHandler.java
  be/src/main/java/team05a/secondhand/errors/handler/ImageExceptionHandler.java
  be/src/main/java/team05a/secondhand/errors/handler/MemberExceptionHandler.java
  be/src/main/java/team05a/secondhand/errors/handler/OauthExceptionHandler.java
  be/src/main/java/team05a/secondhand/errors/handler/StatusExceptionHandler.java
  be/src/main/java/team05a/secondhand/filter/JwtAuthorizationFilter.java
  be/src/main/java/team05a/secondhand/image/data/entity/ProductImage.java
  be/src/main/java/team05a/secondhand/image/repository/ImageRepository.java
  be/src/main/java/team05a/secondhand/image/service/ImageService.java
  be/src/main/java/team05a/secondhand/jwt/JwtTokenProvider.java
  be/src/main/java/team05a/secondhand/member/resolver/LoginArgumentResolver.java
  be/src/main/java/team05a/secondhand/member/resolver/MemberId.java
  be/src/main/java/team05a/secondhand/product/controller/ProductController.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductCreateRequest.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductCreateResponse.java
  be/src/main/java/team05a/secondhand/product/data/entity/Product.java
  be/src/main/java/team05a/secondhand/product/repository/ProductRepository.java
  be/src/main/java/team05a/secondhand/product/service/ProductService.java
  be/src/main/java/team05a/secondhand/status/data/entity/Status.java
  be/src/main/java/team05a/secondhand/status/repository/StatusRepository.java
  be/src/main/resources/data.sql
  be/src/test/java/team05a/secondhand/AcceptanceTest.java
  be/src/test/java/team05a/secondhand/ControllerTestSupport.java
  be/src/test/java/team05a/secondhand/DatabaseCleanup.java
  be/src/test/java/team05a/secondhand/IntegrationTestSupport.java
  be/src/test/java/team05a/secondhand/address/controller/AddressControllerTest.java
  be/src/test/java/team05a/secondhand/address/integration/AddressTest.java
  be/src/test/java/team05a/secondhand/address/repository/AddressRepositoryTest.java
  be/src/test/java/team05a/secondhand/address/service/AddressServiceTest.java
  be/src/test/java/team05a/secondhand/category/controller/CategoryControllerTest.java
  be/src/test/java/team05a/secondhand/category/integration/CategoryTest.java
  be/src/test/java/team05a/secondhand/category/repository/CategoryRepositoryTest.java
  be/src/test/java/team05a/secondhand/category/service/CategoryServiceTest.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/image/repository/ImageRepositoryTest.java
  be/src/test/java/team05a/secondhand/image/service/ImageServiceTest.java
  be/src/test/java/team05a/secondhand/product/controller/ProductControllerTest.java
  be/src/test/java/team05a/secondhand/product/integration/ProductTest.java
  be/src/test/java/team05a/secondhand/product/repository/ProductRepositoryTest.java
  be/src/test/java/team05a/secondhand/product/service/ProductServiceTest.java
  be/src/test/java/team05a/secondhand/status/repository/StatusRepositoryTest.java
Labels: ✨feat, ✅test, ✏️review

#26 [BE] 회원 주소 조회 기능 구현
  be/src/main/java/team05a/secondhand/member/controller/MemberController.java
  be/src/main/java/team05a/secondhand/member/service/MemberService.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/member/integration/MemberIntegrationTest.java
Labels: ✨feat

#31 [BE] 제품 상세보기 기능 구현
  be/src/main/java/team05a/secondhand/address/data/dto/AddressResponse.java
  be/src/main/java/team05a/secondhand/address/data/dto/ProductAddressResponse.java
  be/src/main/java/team05a/secondhand/category/data/dto/ProductCategoryResponse.java
  be/src/main/java/team05a/secondhand/image/data/dto/ProductImageResponse.java
  be/src/main/java/team05a/secondhand/image/repository/ImageRepository.java
  be/src/main/java/team05a/secondhand/image/service/ImageService.java
  be/src/main/java/team05a/secondhand/member/resolver/LoginArgumentResolver.java
  be/src/main/java/team05a/secondhand/product/controller/ProductController.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductDetailResponse.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductResponse.java
  be/src/main/java/team05a/secondhand/product/service/ProductService.java
  be/src/main/java/team05a/secondhand/status/data/dto/StatusResponse.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/product/integration/ProductTest.java
Labels: ✨feat, ✅test

#32 [BE] 상품 삭제 API 구현
  be/build.gradle
  be/src/main/java/team05a/secondhand/errors/exception/ImageNotFoundException.java
  be/src/main/java/team05a/secondhand/errors/handler/ImageExceptionHandler.java
  be/src/main/java/team05a/secondhand/image/repository/ImageRepository.java
  be/src/main/java/team05a/secondhand/image/service/ImageService.java
  be/src/main/java/team05a/secondhand/product/controller/ProductController.java
  be/src/main/java/team05a/secondhand/product/data/entity/Product.java
  be/src/main/java/team05a/secondhand/product/repository/ProductRepository.java
  be/src/main/java/team05a/secondhand/product/service/ProductService.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/image/repository/ImageRepositoryTest.java
  be/src/test/java/team05a/secondhand/product/controller/ProductControllerTest.java
  be/src/test/java/team05a/secondhand/product/integration/ProductTest.java
  be/src/test/java/team05a/secondhand/product/repository/ProductRepositoryTest.java
  be/src/test/java/team05a/secondhand/product/service/ProductServiceTest.java
Labels: ✨feat, ✅test, ✏️review

#34 chore: import 추가
  be/src/main/java/team05a/secondhand/image/repository/ImageRepository.java
Labels: 🐛fix

#35 fix: 쓰지 않는 메서드 삭제
  be/src/test/java/team05a/secondhand/product/integration/ProductTest.java
Labels: 🐛fix

#48 [BE] 회의 사항 반영
  be/docker-compose.yml
  be/src/main/java/team05a/secondhand/config/FilterConfig.java
  be/src/main/java/team05a/secondhand/filter/CorsFilter.java
  be/src/main/java/team05a/secondhand/filter/JwtAuthorizationFilter.java
  be/src/main/java/team05a/secondhand/member/data/dto/MemberAddressResponse.java
  be/src/main/java/team05a/secondhand/member/data/dto/MemberResponse.java
  be/src/main/java/team05a/secondhand/member/resolver/LoginArgumentResolver.java
  be/src/main/java/team05a/secondhand/member/service/MemberService.java
  be/src/main/java/team05a/secondhand/member_address/data/entity/MemberAddress.java
  be/src/main/java/team05a/secondhand/product/controller/ProductController.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductDetailResponse.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductResponse.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductSellerResponse.java
  be/src/main/java/team05a/secondhand/product/service/ProductService.java
  be/src/main/java/team05a/secondhand/status/controller/StatusController.java
  be/src/main/java/team05a/secondhand/status/service/StatusService.java
  be/src/test/java/team05a/secondhand/member/integration/MemberIntegrationTest.java
  be/src/test/java/team05a/secondhand/product/integration/ProductTest.java
  be/src/test/java/team05a/secondhand/status/integration/StatusIntegrationTest.java
Labels: ♻️refactor

#53 [BE] 상품 목록 조회 API 구현
  be/build.gradle
  be/src/main/generated/team05a/secondhand/member/data/entity/QMember.java
  be/src/main/generated/team05a/secondhand/product/data/entity/QProduct.java
  be/src/main/java/team05a/secondhand/address/data/dto/AddressListResponse.java
  be/src/main/java/team05a/secondhand/address/data/dto/ListAddressResponse.java
  be/src/main/java/team05a/secondhand/config/QueryDslConfig.java
  be/src/main/java/team05a/secondhand/filter/JwtAuthorizationFilter.java
  be/src/main/java/team05a/secondhand/product/controller/ProductController.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductListResponse.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductReadResponse.java
  be/src/main/java/team05a/secondhand/product/repository/ProductRepository.java
  be/src/main/java/team05a/secondhand/product/repository/ProductRepositoryCustom.java
  be/src/main/java/team05a/secondhand/product/repository/ProductRepositoryImpl.java
  be/src/main/java/team05a/secondhand/product/service/ProductService.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/product/controller/ProductControllerTest.java
  be/src/test/java/team05a/secondhand/product/integration/ProductTest.java
  be/src/test/java/team05a/secondhand/product/repository/ProductRepositoryTest.java
  be/src/test/java/team05a/secondhand/product/service/ProductServiceTest.java
Labels: ✨feat, ✅test, ✏️review

#52 [BE]: 닉네임 업데이트 기능 구현
  be/src/main/java/team05a/secondhand/member/controller/MemberController.java
  be/src/main/java/team05a/secondhand/member/data/dto/MemberNicknameUpdateRequest.java
  be/src/main/java/team05a/secondhand/member/data/entity/Member.java
  be/src/main/java/team05a/secondhand/member/service/MemberService.java
  be/src/test/java/team05a/secondhand/member/integration/MemberIntegrationTest.java
Labels: ✨feat

#59 [BE]: 관심 상품 추가 / 제거 구현
  be/src/main/java/team05a/secondhand/member/controller/MemberController.java
  be/src/main/java/team05a/secondhand/wish/controller/WishController.java
  be/src/main/java/team05a/secondhand/wish/data/dto/WishRequest.java
  be/src/main/java/team05a/secondhand/wish/data/entity/Wish.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepository.java
  be/src/main/java/team05a/secondhand/wish/service/WishService.java
  be/src/test/java/team05a/secondhand/member/integration/MemberIntegrationTest.java
  be/src/test/java/team05a/secondhand/wish/integration/WishTest.java
Labels: ✨feat

#61 [BE]: 관심 여부 조회 기능 구현
  be/src/main/java/team05a/secondhand/wish/controller/WishController.java
  be/src/main/java/team05a/secondhand/wish/data/dto/WishResponse.java
  be/src/main/java/team05a/secondhand/wish/service/WishService.java
  be/src/test/java/team05a/secondhand/member/integration/MemberIntegrationTest.java
  be/src/test/java/team05a/secondhand/wish/integration/WishTest.java
Labels: ✨feat

#62 [BE] redis를 이용하여 조회수 구현
  be/src/main/java/team05a/secondhand/config/FilterConfig.java
  be/src/main/java/team05a/secondhand/errors/exception/ProductViewNotFoundException.java
  be/src/main/java/team05a/secondhand/errors/handler/ProductExceptionHandler.java
  be/src/main/java/team05a/secondhand/filter/JwtAuthorizationFilter.java
  be/src/main/java/team05a/secondhand/oauth/service/OauthService.java
  be/src/main/java/team05a/secondhand/product/service/ProductService.java
  be/src/main/java/team05a/secondhand/redis/repository/RedisRepository.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/product/repository/ProductRepositoryTest.java
  be/src/test/java/team05a/secondhand/product/service/ProductServiceTest.java
  be/src/test/java/team05a/secondhand/redis/repository/RedisRepositoryTest.java
Labels: ✨feat, ✅test, ✏️review

#69 [BE] 판매 목록 조회 API 구현
  be/src/main/java/team05a/secondhand/member/controller/MemberController.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductListStatsResponse.java
  be/src/main/java/team05a/secondhand/product/data/dto/ProductReadResponse.java
  be/src/main/java/team05a/secondhand/product/repository/ProductRepositoryCustom.java
  be/src/main/java/team05a/secondhand/product/repository/ProductRepositoryImpl.java
  be/src/main/java/team05a/secondhand/product/service/ProductService.java
  be/src/test/java/team05a/secondhand/product/repository/ProductRepositoryTest.java
Labels: ✨feat

#76 [BE]: 관심상품 카테고리 조회 기능 구현
  be/src/main/java/team05a/secondhand/member/data/entity/Member.java
  be/src/main/java/team05a/secondhand/wish/controller/WishController.java
  be/src/main/java/team05a/secondhand/wish/data/dto/WishCategoryResponse.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepository.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepositoryCustom.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepositoryImpl.java
  be/src/main/java/team05a/secondhand/wish/service/WishService.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/wish/integration/WishTest.java
Labels: ✨feat

#78 [BE]: 관심상품 조회 기능 구현
  be/src/main/java/team05a/secondhand/wish/controller/WishController.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepositoryCustom.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepositoryImpl.java
  be/src/main/java/team05a/secondhand/wish/service/WishService.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/wish/integration/WishTest.java
Labels: ✨feat, ✅test

#80 [BE]: release에 dev 병합
  be/src/main/java/team05a/secondhand/jwt/Jwt.java
  be/src/main/java/team05a/secondhand/jwt/JwtTokenProvider.java
  be/src/main/java/team05a/secondhand/member/data/entity/Member.java
  be/src/main/java/team05a/secondhand/wish/controller/WishController.java
  be/src/main/java/team05a/secondhand/wish/data/dto/WishCategoryResponse.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepository.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepositoryCustom.java
  be/src/main/java/team05a/secondhand/wish/repository/WishRepositoryImpl.java
  be/src/main/java/team05a/secondhand/wish/service/WishService.java
  be/src/test/java/team05a/secondhand/fixture/FixtureFactory.java
  be/src/test/java/team05a/secondhand/wish/integration/WishTest.java
Labels: ✨feat
